version: '2'

services: 
#  go:
#    image: goora:latest
#    volumes:
#      - ./12.2/golang1.10stretch:/goora
  
  oracledb:
    image: container-registry.oracle.com/database/enterprise:12.2.0.1
    environment: 
      - NLS_LANG=AMERICAN_AMERICA.UTF8
    volumes:
      - oracle_data:/ORCL
    ports:
      - 1521:1521
      - 5500:5500

  oracle-collector:
    container_name: oracle-collector
    build: ./12.2/golang1.10stretch
    restart: on-failure
    command: go run main.go
    environment: 
      - DATA_SOURCE_NAME=C##demouser/hemligt@oracledb:1521/ORCLCDB.localdomain
      - NLS_LANG=AMERICAN_AMERICA.UTF8
    ports:
      - "8000:8000"
      - "9161:9161"
    links: 
      - oracledb:oracledb
    working_dir: /go/src/oracle-collector
    volumes:
      - ./12.2/golang1.10stretch/oracle-collector:/go/src/oracle-collector

  tyr-collector:
    container_name: tyr-collector
    build: ./12.2/golang1.10stretch
    restart: on-failure
    command: go run main.go
    environment: 
      - DATA_SOURCE_NAME=petehene/Kh29prH9MEbA@tyr:1521/PRD_EDM
      - NLS_LANG=AMERICAN_AMERICA.UTF8
    ports:
      - "8002:8000"
      - "9162:9161"
    extra_hosts: 
      - tyr:10.156.151.234
    working_dir: /go/src/oracle-collector
    volumes:
      - ./12.2/golang1.10stretch/oracle-collector:/go/src/oracle-collector

  metrics-gateway:
      container_name: gateway
      image: prom/pushgateway
      ports:
        - 9091:9091

  prometheus-server:
      container_name: promserver
      image: prom/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
        - 9090:9090
      links:
        - metrics-gateway:metrics-gateway
        - oracle-collector:oracle-collector
        - tyr-collector:tyr-collector
      volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_data:/prometheus

  grafana-ui:
      container_name: grafana
      image: grafana/grafana
      ports:
        - 3000:3000
      volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana/provisioning/:/etc/grafana/provisioning/
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=secret
      links:
        - prometheus-server:prometheus-server

volumes:
  prometheus_data: {}
  grafana_data: {}
  oracle_data: {}